# Generated by Django 2.1.1 on 2018-10-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ManyToManyField(related_name='_folder_folder_+', to='printapi.Folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapi.Folder'),
        ),
    ]
