# Generated by Django 2.1.1 on 2018-10-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0002_auto_20181005_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='printapi.Folder'),
            preserve_default=False,
        ),
    ]
