# Generated by Django 2.1.1 on 2018-11-07 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printapi', '0007_auto_20181010_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Found',
            new_name='Founds',
        ),
    ]
