# Generated by Django 2.1.1 on 2018-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0008_auto_20181107_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='npages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
