# Generated by Django 2.1.1 on 2018-11-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0009_auto_20181107_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='npages',
            new_name='npages',
        ),
    ]
