# Generated by Django 2.1.1 on 2018-11-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0011_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default='PracticaEstructura', max_length=50, null=True),
        ),
    ]
