# Generated by Django 2.1.1 on 2018-11-15 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printapi', '0012_auto_20181114_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.FloatField()),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='printapi.Folder')),
                ('found', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('npages', models.IntegerField()),
                ('amount', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printapi.File')),
            ],
        ),
    ]
