# Generated by Django 2.1.1 on 2018-11-15 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printapi', '0013_fundtransaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='history',
            name='file',
        ),
        migrations.AddField(
            model_name='history',
            name='file',
            field=models.ManyToManyField(to='printapi.File'),
        ),
    ]
