# Generated by Django 2.1.1 on 2018-11-15 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0014_auto_20181115_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='file',
        ),
        migrations.AddField(
            model_name='history',
            name='documentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='printapi.File'),
        ),
        migrations.AddField(
            model_name='history',
            name='doubleSided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fundtransaction',
            name='file',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='printapi.Folder'),
        ),
    ]
