# Generated by Django 2.1.1 on 2018-11-15 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printapi', '0015_auto_20181115_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Founds',
            new_name='Funds',
        ),
    ]
