# Generated by Django 2.1.1 on 2018-12-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0016_auto_20181115_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundtransaction',
            old_name='found',
            new_name='user',
        ),
    ]
