# Generated by Django 2.1.1 on 2018-12-13 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapi', '0017_auto_20181211_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundtransaction',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fundtransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='FundTransaction',
        ),
    ]
